= Combinators


== `,`

[source,css]
----
selector-1, selector-2
{
	property: value;
}
----

=== Example 1

[source,css]
----
div, p
{
	property: value;
}
----

Same as:

[source,css]
----
div
{
	property: value;
}

p
{
	property: value;
}
----

== `.`

[source,css]
----
selector-1.selector-2
{
	property: value;
}
----

=== Example 1

Select all `<h1>` elements of class `class-name`:

[source,css]
----
h1.class-name
{
    property: value;
    property: value;
}
----

[source,html]
----
<h1 class="class-name">
    ...
</h1>
----

=== Example 2

Select the element with id `id-name` and both the classes `class-name-1` and `class-name-2`:

[source,css]
----
#id-name.class-name-1.class-name-2
{
    property: value;
    property: value;
}
----

[source,html]
----
<h1 id="id-name" class="class-name-1 class-name-2">
    ...
</h1>
----

== Descendant Selector (`[space] `)



[source,css]
----
selector-1 selector-2
{
	property: value;
}
----

=== Example 1

Select all `<p>` elements within a `<div>` parent element:

[source,css]
----
div p
{
	property: value;
}
----

[source,html]
----
<div>
    <p></p> <!-- included -->

    <h1>
    	<p></p> <!-- included -->
    </h1>

    <div>
    	<p></p> <!-- included -->
    </div>
</div>
----

== Child Selector (`>` greater-than)

[quote,https://www.geeksforgeeks.org/what-is-greater-than-sign-selector-in-css/]
____
selects only those elements which are direct children of a parent. 
It looks only one level down the markup structure and not further deep down. 
Elements which are not the direct child of the specified parent is not selected.
____

[source,css]
----
selector-1 > selector-2
{
	property: value;
}
----

=== Example 1

Select all `<p>` elements within a `<div>` direct parent element:

[source,css]
----
div > p
{
	property: value;
}
----

[source,html]
----
<div>
    <p></p> <!-- included -->

    <h1>
    	<p></p> <!-- NOT included -->
    </h1>

    <div>
    	<p></p> <!-- included -->
    </div>
</div>
----

== Adjacent Sibling Selector (`+`)

[comment]
--
=== Example 1 (TODO)

Selects the first `<p>` element that are placed immediately after `<div>` elements:

[source,css]
----
div + p
{
	property: value;
}
----

[source,html]
----
<div>
    <p></p> <!--  -->

    <h1>
    	<p></p> <!--   -->
    </h1>

    <div>
    	<p></p> <!--  -->
    </div>
</div>
----
--

== General Sibling Selector (`~`)

[comment]
--
=== Example 1 (TODO)

Selects every `<ul>` element that are preceded by a `<li>` element:

[source,css]
----
ul ~ li
{
	property: value;
}
----

[source,html]
----
<ul>
    <li></li>
    <li></li>
</ul>
----
--