= Coding Cookbook
:author: Alexandry Augustin
// :sectnums:
// :toc: preamble

// Recipes

This repository is my personal library of useful code snippets, examples, and programs I have built over the years in various programming languages.

== Motivation

https://github.com/DevDungeon/Cookbook[Coding cookbooks] are my preferred way of learning new programming languages, libraries, and frameworks.

"A cookbook in the programming context is collection of tiny programs that each demonstrate a particular programming concept. The Cookbook Method is the process of learning a programming language by building up a repository of small programs that implement specific programming concepts."
-- https://github.com/DevDungeon/Cookbook[John "NanoDano" Leon]

I frequently use this repository for quick reference and as building blocks for bigger projects. 

== License

All source code is made available under the MIT license. 
You can freely use and modify the code, without warranty, so long as you provide attribution to the authors. 
See link:./LICENSE[LICENSE] for the full license text.