= Boostrap 5
// :stylesheet: bootstrap.min.css
:url-website: https://getbootstrap.com/
:url-docs: https://getbootstrap.com/docs/
:url-github: https://github.com/twbs/bootstrap
:url-examples: https://getbootstrap.com/docs/5.0/examples/

++++
<link rel="stylesheet" href="bootstrap.min.css">
++++

{url-website}[[website\]]
{url-docs}[[docs\]]
{url-github}[[github\]]
{url-examples}[[examples\]]

https://stackoverflow.com/questions/42252443/vertical-align-center-in-bootstrap-4

https://startbootstrap.com/

https://suyashlakhotia.com/blog/2017/05/04/bootstrap-cards.html

https://suyashlakhotia.com/BootstrapCards/

== Installation

=== NPM

[source,bash]
----
npm install bootstrap@5.1.3 --save-dev
----

=== CDN

https://www.jsdelivr.com/package/npm/bootstrap

https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/

[source,html]
----
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
----

== Breakpoints

|===
| Class | Breakpoint | Dimensions

| _None_
| X-Small
| <576px

| `sm`
| Small
| ≥576px

| `md`
| Medium
| ≥768px

| `lg`
| Large
| ≥992px

| `xl`
| Extra large
| ≥1200px

| `xxl`
| Extra extra large (new)
| ≥1400px
|===

== Borders

....
border-[border]
....

`border`::
* `top`: {empty}
* `end`: {empty}
* `bottom`: {empty}
* `start`: {empty}

== Grid

|===
| | Extra small <576px | Small ≥576px | Medium ≥768px | Large ≥992px | X-Large≥1200px | XX-Large ≥1400px

| `.container`
| 100%
| 540px
| 720px
| 960px
| 1140px
| 1320px

| `.container-sm`
| 100%
| 540px
| 720px
| 960px
| 1140px
| 1320px

| `.container-md`
| 100%
| 100%
| 720px
| 960px
| 1140px
| 1320px

| `.container-lg`
| 100%
| 100%
| 100%
| 960px
| 1140px
| 1320px

| `.container-xl`
| 100%
| 100%
| 100%
| 100%
| 1140px
| 1320px

| `.container-xxl`
| 100%
| 100%
| 100%
| 100%
| 100%
| 1320px

| `.container-fluid`
| 100%
| 100%
| 100%
| 100%
| 100%
| 100%
|===

> "Rows are wrappers for columns." -- https://getbootstrap.com/docs/5.1/layout/grid/

....
container
container-[breakpoint]
container-fluid
....

....
row-[breakpoint]-[size]
row-[breakpoint]-auto

col-[breakpoint]-[size]
col-[breakpoint]-auto

row-cols-[breakpoint]-[size]
....

`size`::
from 1 to 12

++++
<div class="container">
  <div class="row">
    <div class="col border">
      Column
    </div>
    <div class="col border">
      Column
    </div>
    <div class="col border">
      Column
    </div>
  </div>
</div>
++++

=== `.gutter`

`gx-*`::
horizontal gutters

`gy-*`::
vertical gutters

`g-*`::
all gutters

== Margin and Padding

....
[property][sides]-[size]
....

`property`::
* `m`: margin
* `p`: padding

`side`::
* `t`: *-top
* `b`: *-bottom

* `s`: (start) *-left in LTR, *-right in RTL
* `e`: (end) *-right in LTR, *-left in RTL

* `x`: both *-left and *-right
* `y`: both *-top and *-bottom

* blank: margin or padding on all 4 sides of the element

`size`::
....
0 - for classes that eliminate the margin or padding by setting it to 0
1 - (by default) for classes that set the margin or padding to $spacer * .25
2 - (by default) for classes that set the margin or padding to $spacer * .5
3 - (by default) for classes that set the margin or padding to $spacer
4 - (by default) for classes that set the margin or padding to $spacer * 1.5
5 - (by default) for classes that set the margin or padding to $spacer * 3
auto - for classes that set the margin to auto
....

== Display

https://getbootstrap.com/docs/5.2/utilities/display/

....
d-[display]
....

`display`::
* `none`: {empty}
* `inline`: {empty}
* `inline-block`: {empty}
* `block`: {empty}
* `grid`: {empty}
* `table`: {empty}
* `table-cell`: {empty}
* `table-row`: {empty}
* `flex`: {empty}
* `inline-flex`: {empty}

== Alignment

....
text-[alignment]
....

`alignment`::
* `center`: {empty}
* `start`: {empty}
* `end`: {empty}