= Background

[source,css]
----
background-image: url("...");
background-repeat: no-repeat;
background-attachment: fixed;
----

== `background-size`

[quote,https://www.w3schools.com/cssref/css3_pr_background-size.php]
____
There are four different syntaxes you can use with this property: 
the keyword syntax ("auto", "cover" and "contain"), 
the one-value syntax (sets the width of the image (height becomes "auto"), 
the two-value syntax (first value: width of the image, second value: height), 
and the multiple background syntax (separated with comma).
____

[quote,https://css-tricks.com/almanac/properties/b/background-size/]
____
`cover` tells the browser to make sure the image *always* covers the entire container, even if it has to stretch the image or cut a little bit off one of the edges. 

`contain`, on the other hand, says to *always* show the whole image, even if that leaves a little space to the sides or bottom.

The default keyword -- `auto` -- tells the browser to automatically calculate the size based on the actual size of the image and the aspect ratio.
____

[source,css]
----
background-size: auto;
background-size: cover;
background-size: contain;

background-size: 100%;       /* set the width, the height is set to auto. */
background-size: 100% 100%;
background-size: auto 100%;
----

== `background-position`

property sets the starting position of a background image.

[source,css]
----
background-position: center; 
----

....
left top
left center
left bottom
right top
right center
right bottom
center top
center center
center bottom 	If you only specify one keyword, the other value will be "center"
....