= JavaScript

== Modules

=== `require()`

[quote,https://stackoverflow.com/questions/9901082/what-is-this-javascript-require]
____
https://nodejs.org/api/modules.html#modules_require[`require()`] is not part of the standard JavaScript API. 
But in Node.js, it's a built-in function
____

[source,javascript]
----
let module_name = require('module_name');
----

=== `module.exports`

[source,javascript]
----
module.exports = ...
----

=== `main()`

[quote,https://mathieularose.com/main-function-in-node-js]
____
Unlike most other programming languages or runtime environments, Node.js doesn't have a built-in special `main` function to designate the entry point of a program. But there is an easy way to achieve this in Node.js [...].

The pattern is to check if the current module is the main module: `require.main === module`. 
If this is true, the current file has been run directly -- as opposed to have been imported by another file -- and in this case we can call the `main` function. 
Example:

[source,javascript]
----
if(require.main === module)
{
	// ...
}
----
____

== JavaScript

`global` replaces `window`

`process` replaces `document`

== Core Modules

`fs`:: {empty}
`path`:: {empty}
`http`:: {empty}
`url`:: {empty}
`querystring`:: {empty}
`events`:: {empty}
`os`:: {empty}
`util`:: {empty}
