= JavaScript Object Notation (JSON)
:toc: left
// :url-website: 
// :url-docs: 
// :url-repo: 
// :url-wiki: 

// {url-website}[[website\]]
// {url-docs}[[docs\]]
// {url-repo}[[repo\]]
// {url-wiki}[[wiki\]]

== Data Types

=== Dates and Time

> "JSON Dates are not dates -- they are Strings" 
-- https://weblog.west-wind.com/posts/2014/jan/06/javascript-json-date-parsing-and-real-dates#json-dates-are-not-dates--they-are-strings

> "JSON itself does not specify how dates should be represented, but JavaScript does. You should use the format emitted by Date's toJSON method [...] ISO 8601" 
-- https://stackoverflow.com/questions/10286204/what-is-the-right-json-date-format

== Comments

> "The JSON is data only, and if you include a comment, then it will be data too." 
-- https://stackoverflow.com/questions/244777/can-comments-be-used-in-json

== `.bson`

[B]inary J[SON]

== Conventions

[,https://stackoverflow.com/questions/9619852/what-is-the-convention-in-json-for-empty-vs-null]
____
It is good programming practice to return an empty array `[]` if the expected return type is an array. 
This makes sure that the receiver of the json can treat the value as an array immediately without having to first check for null. 
It's the same way with empty objects using open-closed braces `{}`.

`Strings`, `Booleans` and `integers` do not have an 'empty' form, so there it is okay to use `null` values.

This is also addressed in Joshua Blochs excellent book "Effective Java". There he describes some very good generic programming practices (often applicable to other programming langages as well). Returning empty collections instead of nulls is one of them.

http://jtechies.blogspot.nl/2012/07/item-43-return-empty-arrays-or.html[Here's a link to that part of his book]
____

