= Directives

// https://www.wittyprogramming.dev/articles/introduction-to-alpinejs/

`x-modelable`:: {empty}
`x-effect`:: (similar to `useEffect()` in React). (See also `$watch` magic command)
* The code will be run right away AND when data changes.
* No knowledge of the previous value
`x-ignore`:: {empty}
`x-cloak`:: {empty}
`x-teleport`:: {empty}
`x-id`:: {empty}

== Initialisation

`x-data`:: {empty}
`x-init`:: {empty}

== Binding

`x-bind:attribute_name` or `:attribute_name`:: [One-way]
//NOTE: `:` is a shorthand syntax `x-bind:` (e.g. `:placeholder` is equivalent to `x-bind:placeholder`).
`x-text`:: [One-way] to the element's `innerText`
`x-html`:: [One-way] to the element's `innerHTML`
`x-model`:: [Two-way]

== Toggle Display

`x-show`:: Toggles the `display:none` element's style depending on the expression's outcome
`x-if`:: Completely removes the element from the DOM but has two significant constraints +
[NOTE]
====
[quote,https://www.wittyprogramming.dev/articles/introduction-to-alpinejs/]
____
Because the Alpine uses the real DOM and not a virtual, the first constraint is that the x-if attribute must be applied on a `<template></template>` tag. Consequently, the second constraint is that the `<template></template>` must have a single element root. The equivalent of the above x-show example using the x-if attribute is:

[source,html]
----
<template x-if="login">
    <div x-text="`welcome ${username}`"></div>
</template>
----
____
====
`x-transition`:: {empty}

== Loops

`x-for`:: {empty} +
NOTE: `x-for` MUST be declared on a `<template>` element.
That `<template>` element MUST contain only one root element.

[source,html]
----
<template x-for="item in items" :key="item">
    <div x-text="item"></div>
</template>
----

[source,html]
----
<template x-for="item in items">
    <div>
        <template x-for="subItem in item.subItems">
            <div x-text="subItem"></div>
        </template>
    </div>
</template>
----

== Events

`x-on:event_name` or `@event_name`:: {empty}
//NOTE: `@` is a shorthand syntax `x-on:` (e.g. `@click` is equivalent to `x-on:click`).

=== Custom Events

TODO

== Accessor

[quote,https://www.alpinejs.dev/directives/ref]
____
`x-ref` in combination with `$refs` is a useful utility for easily accessing DOM elements directly. 
It's most useful as a replacement for APIs like `getElementById` and `querySelector`."
____

`x-ref`:: {empty}