= Directives

// https://www.wittyprogramming.dev/articles/introduction-to-alpinejs/

`x-modelable`:: {empty}
`x-effect`:: (similar to `useEffect()` in React).
`x-ignore`:: {empty}
`x-cloak`:: {empty}
`x-teleport`:: {empty}
`x-id`:: {empty}

== Initialisation

`x-data`:: {empty}
`x-init`:: {empty}

== Binding

Dynamically set HTML attributes on an element.

`x-model`:: Two-way binding
`x-bind[:attribute_name]`:: One-way binding
`x-text`:: One-way binding to the element's `innerText`
`x-html`:: One-way binding to the element's `innerHTML`

== Toggle Display

`x-show`:: Toggles the `display:none` element's style depending on the expression's outcome
`x-if`:: Completely removes the element from the DOM but has two significant constraints +
[NOTE]
====
[quote,https://www.wittyprogramming.dev/articles/introduction-to-alpinejs/]
____
Because the Alpine uses the real DOM and not a virtual, the first constraint is that the x-if attribute must be applied on a `<template></template>` tag. Consequently, the second constraint is that the `<template></template>` must have a single element root. The equivalent of the above x-show example using the x-if attribute is:

[source,html]
----
<template x-if="login">
    <div x-text="`welcome ${username}`"></div>
</template>
----
____
====
`x-transition`:: {empty}

== Loops

`x-for`:: {empty} +
NOTE: `x-for` MUST be declared on a `<template>` element.
That `<template>` element MUST contain only one root element.

[source,html]
----
<template x-for="item in items" :key="item">
    <div x-text="item"></div>
</template>
----

[source,html]
----
<template x-for="item in items">
    <div>
        <template x-for="subItem in item.subItems">
            <div x-text="subItem"></div>
        </template>
    </div>
</template>
----

== Events

`x-on:event`:: {empty}

NOTE: `@` is a shorthand syntax `x-on:` (e.g. `@click` instead of `x-on:click`).

== Accessor

> "`x-ref` in combination with `$refs` is a useful utility for easily accessing DOM elements directly. 
It's most useful as a replacement for APIs like `getElementById` and `querySelector`."
-- https://www.alpinejs.dev/directives/ref

`x-ref`:: {empty}